name: build
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run ESLint
        run: npm run lint

      - name: Type check
        run: npm run lint:tsc

      - name: Run Jest tests
        run: npm run test:ci

      - name: Build app
        run: npm run build
